// 詢價通知信 / 客戶確認信的 HTML 模板
// 所有來自表單的欄位都必須經過 escapeHtml，避免使用者輸入的 HTML 被信件客戶端當成真的內容顯示（釣魚連結、偽造按鈕）

export type InquiryEmailItem = {
  modelNumber: string;
  nameZhTw?: string;
  nameZhCn?: string;
  nameEn?: string;
  quantity: number;
};

export type InquiryEmailData = {
  name: string;
  email: string;
  companyName: string;
  country: string;
  phone?: string;
  message?: string;
  items: InquiryEmailItem[];
};

const HTML_ESCAPES: Record<string, string> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;'
};

export function escapeHtml(value: unknown): string {
  return String(value ?? '').replace(/[&<>"']/g, (char) => HTML_ESCAPES[char]);
}

// 信件標題為純文字，移除換行字元避免標頭注入
export function sanitizeSubject(value: string): string {
  return value.replace(/[\r\n]+/g, ' ').trim();
}

function buildItemRows(items: InquiryEmailItem[]) {
  return items
    .map(
      (item) => `
        <tr>
          <td style="border: 1px solid #cbd5e1; padding: 8px;"><strong>${escapeHtml(item.modelNumber)}</strong></td>
          <td style="border: 1px solid #cbd5e1; padding: 8px;">${escapeHtml(item.nameZhTw || item.nameEn || item.nameZhCn)}</td>
          <td style="border: 1px solid #cbd5e1; padding: 8px;"><strong>${escapeHtml(item.quantity)}</strong> units</td>
        </tr>
      `
    )
    .join('');
}

// A. 寄給管理者的「新詢價通知信」
export function buildAdminMailHtml(data: InquiryEmailData) {
  const itemRows = buildItemRows(data.items);

  return `
        <h2>Xie Huang Enterprise Co., Ltd. - New RFQ Inquiry Notification</h2>
        <p>Dear Admin,</p>
        <p>A new Request for Quote (RFQ) has been submitted via the website catalog. Below are the details:</p>

        <h3>Customer Contact Details</h3>
        <table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%; max-width: 600px; border-color: #cbd5e1;">
          <tr>
            <td style="background-color: #f8fafc; font-weight: bold; width: 30%;">Contact Name</td>
            <td>${escapeHtml(data.name)}</td>
          </tr>
          <tr>
            <td style="background-color: #f8fafc; font-weight: bold;">Email Address</td>
            <td>${escapeHtml(data.email)}</td>
          </tr>
          <tr>
            <td style="background-color: #f8fafc; font-weight: bold;">Company Name</td>
            <td>${escapeHtml(data.companyName)}</td>
          </tr>
          <tr>
            <td style="background-color: #f8fafc; font-weight: bold;">Country / Region</td>
            <td>${escapeHtml(data.country)}</td>
          </tr>
          <tr>
            <td style="background-color: #f8fafc; font-weight: bold;">Telephone</td>
            <td>${escapeHtml(data.phone || 'N/A')}</td>
          </tr>
          <tr>
            <td style="background-color: #f8fafc; font-weight: bold;">Message Detail</td>
            <td>${escapeHtml(data.message || 'N/A')}</td>
          </tr>
        </table>

        <h3>Inquired Parts List</h3>
        <table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%; max-width: 800px; border-color: #cbd5e1; margin-top: 15px;">
          <thead>
            <tr style="background-color: #f1f5f9;">
              <th align="left">Model Number</th>
              <th align="left">Product Name</th>
              <th align="left">Quantity Requested</th>
            </tr>
          </thead>
          <tbody>
            ${itemRows}
          </tbody>
        </table>

        <hr style="border: 0; border-top: 1px solid #e2e8f0; margin-top: 30px;" />
        <p style="font-size: 0.85rem; color: #64748b;">This email was automatically generated by the Xie Huang Enterprise site system. You can reply directly to this email to contact the buyer at ${escapeHtml(data.email)}.</p>
      `;
}

// B. 寄給客戶的「確認信」
export function buildCustomerMailHtml(data: InquiryEmailData) {
  const itemRows = buildItemRows(data.items);

  return `
        <h2>Thank You for Your Inquiry</h2>
        <p>Dear ${escapeHtml(data.name)},</p>

        <p>Thank you for contacting <strong>Xie Huang Enterprise Co., Ltd.</strong> (Taiwan). We have successfully received your Request for Quote (RFQ). Our sales representative is reviewing your requirements and will contact you with the pricing and details within 24 hours.</p>

        <p>Here is a summary of your requested motorcycle parts for your reference:</p>

        <h3>Requested Parts Summary</h3>
        <table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%; max-width: 600px; border-color: #cbd5e1;">
          <thead>
            <tr style="background-color: #f1f5f9;">
              <th align="left">Model Number</th>
              <th align="left">Product Name</th>
              <th align="left">Quantity</th>
            </tr>
          </thead>
          <tbody>
            ${itemRows}
          </tbody>
        </table>

        <h3>Your Messages / Requirements</h3>
        <blockquote style="border-left: 4px solid #cbd5e1; margin-left: 0; padding-left: 15px; color: #475569; font-style: italic;">
          ${escapeHtml(data.message || 'No additional message.')}
        </blockquote>

        <p>If you have any technical drawings, OEM samples, or additional specifications to provide, please reply directly to this email or send them to sales@xh-motorparts.com.</p>

        <p>Sincerely,</p>
        <p>
          <strong>Xie Huang Enterprise Co., Ltd.</strong><br />
          Taiwan Motorcycle Parts Manufacturer Since 1990<br />
          Website: xh-motorparts.com
        </p>
      `;
}
